GET http://localhost:3900/api/v1/admin/search/toky&product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdlMTJlMzE5MGJhZDYxODYxZGYwMCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicmVnaXN0ZXJfZGF0ZSI6IjIwMjItMDQtMjZUMTI6MTA6MjIuMjM2WiIsImlhdCI6MTY1MTA0ODYyMSwiZXhwIjoxNjUxMTM1MDIxfQ.CA6C2ArGF-U7TclPA-ZI88ALG-Hm2zSJevYl_qePMbM