PATCH http://localhost:3900/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdlMTJlMzE5MGJhZDYxODY0NWYwMSIsImVtYWlsIjoiZXVzdGFxaW9AZ21haWwuY29tIiwicmVnaXN0ZXJfZGF0ZSI6IjIwMjItMDQtMjZUMTI6MTA6MjIuMjM2KzAwOjAwIn0.eO6aysIeaeobIsNFJ5Sgj0JwzLG0tfmY1T4clFK87B4