PATCH http://localhost:3900/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdjYzM1YzUwNjJmOWQyNjJhYjU3ZiIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA0LTI2VDEwOjQwOjUzLjg0OVoiLCJpYXQiOjE2NTA5NzAwNTAsImV4cCI6MTY1MTA1NjQ1MH0.KiAfv0F6OPeKOcvZq8OODOquRQEB-w-CTmrjwL3Mkv0