
POST http://localhost:3900/api/v1/product
content-type: application/json

{
    "name" : "Prueba Imagen",
    "price" : 100,
    "description" : "Descripcion larga",
    "short_description" : "Descripcion corta",
    "state" : "old",
    "stock" : 5,
    "categories" : ["realidad virtual"],
    "type" : "novela ligera",
    "number_sales" : 5,
    "authors" : "Prueba",
    "editorial" : "Prueba",
    "series" : "Prueba",
    "comments" : []
}