POST http://localhost:3900/api/v1/card HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzRmNzlkYTM5MmJiNWNjYzNhNWFkNSIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA1LTA2VDEwOjI1OjMzLjg5MloiLCJpYXQiOjE2NTE4MzQzNzksImV4cCI6MTY1MTg0MTU3OX0.8PKEWl05jM88wm5SR1e0AG8xgRwwTQdvDwT9gvuS1sY

{
    "card_name" : "Adrian Arnaiz Fernandez",
    "expiration_date" : "03/22",
    "number_card" : "6218463545801562"
}