POST http://localhost:3900/api/v1/card HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjY5ODJiNmZkMDllZmQwMDMxZDJlOCIsImVtYWlsIjoicHJ1ZWJhRGVsZXRlQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA0LTI1VDEyOjQ2OjM1LjI5N1oiLCJpYXQiOjE2NTA4OTA3OTUsImV4cCI6MTY1MDk3NzE5NX0.q6zAVoUVLOObFF1j37Om5hGLGdPeUCEeX55JJuVhYpw

{
    "card_name" : "Adrian Arnaiz Fernandez",
    "expiration_date" : "03/22",
    "number_card" : "5218463545801562"
}