POST http://localhost:3900/api/v1/card HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdlMTc3ZjczMDE0MjgzZjkwNmQyNCIsImVtYWlsIjoidXN1YXJpb0BnbWFpbC5jb20iLCJyZWdpc3Rlcl9kYXRlIjoiMjAyMi0wNC0yNlQxMjoxMTozNS42ODdaIiwiaWF0IjoxNjUwOTc1MTY5LCJleHAiOjE2NTEwNjE1Njl9._8wH5TSl3mxzumEyOGJ_OA2bwmvlNuEKUSt_m3SEPlM

{
    "card_name" : "Adrian Arnaiz Fernandez",
    "expiration_date" : "03/22",
    "number_card" : "6218463545801562"
}