POST http://localhost:3900/api/v1/address HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdkYTMwMmY2ZTYyYmM2NmNkOGU4OSIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA0LTI2VDExOjQwOjMyLjc2NVoiLCJpYXQiOjE2NTA5NzMyMzIsImV4cCI6MTY1MTA1OTYzMn0.ywd6Le2MS4h6DdBw53t4mzT1r2qr6CzKLVZwLAvRelU

{
    "name" : "Calle Tu Casa4",
    "number" : "60",
    "name_person" : "Adrian Arnaiz Fernandez",
    "location" : "Móstoles"
}