DELETE http://localhost:3900/api/v1/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdkMDM4YWU0NGI4ZDA5NWQ5OTk0NSIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA0LTI2VDEwOjU4OjAwLjUwNFoiLCJpYXQiOjE2NTA5NzA2ODAsImV4cCI6MTY1MTA1NzA4MH0.zEyorFefz8zBgrnvBQaM2eJxS6jLXS-l8dRwJJUJQ-E