DELETE http://localhost:3900/api/v1/comment/6267d3212a3368e924ce86d6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdkMTgyN2M3MDlkZjM3MDY0M2UyNiIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA0LTI2VDExOjAzOjMwLjY1NVoiLCJpYXQiOjE2NTA5NzEyMzQsImV4cCI6MTY1MTA1NzYzNH0.DqGg_sX-bbvdxClvDRbqrd5Ea0eZXKYpR14K2cyMNNA