DELETE http://localhost:3900/api/v1/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjY5ZDE5YjBkNDcyNzE0MDZiZWFkNyIsImVtYWlsIjoiZGVsZXRlMkBnbWFpbC5jb20iLCJyZWdpc3Rlcl9kYXRlIjoiMjAyMi0wNC0yNVQxMzowNzozNy43NDZaIiwiaWF0IjoxNjUwODkyMDU3LCJleHAiOjE2NTA5Nzg0NTd9.qTHGe91InvO4gGhJBr-RfRFzkQdI0m9kHyOGvxZGQoI