PUT  http://localhost:3900/api/v1/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjJhMTYwZmUxNmNmZjYwMzVmZjJhOSIsImVtYWlsIjoiYWRyaWFuNUBnbWFpbC5jb20iLCJyZWdpc3Rlcl9kYXRlIjoiMjAyMi0wNC0yMlQxMjozNjo0OC4wNjRaIiwiaWF0IjoxNjUwOTYwMzQyLCJleHAiOjE2NTEwNDY3NDJ9.gHSnMdsNUAIV8Uagt_ZIxa7iNqPToMonUtoode4kuP4

{
    "delivery_address" : "6267aeb97e598b9c84c08478",
    "billing" : "6267aea77e598b9c84c08474",
    "telephone" : 123456789
}