GET http://localhost:3900/api/v1/admin/roles HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdlMTJlMzE5MGJhZDYxODYxZGYwMCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicmVnaXN0ZXJfZGF0ZSI6IjIwMjItMDQtMjZUMTI6MTA6MjIuMjM2WiIsImlhdCI6MTY1MDk3NTA2NiwiZXhwIjoxNjUxMDYxNDY2fQ.B-KingQ-EKt61p5QgZCX80E4LPFt4uZXQP14gPHjH0w