GET http://localhost:3900/api/v1/admin/users HTTP/1.1
# GET http://localhost:3900/api/v1/admin/users/Disabled HTTP/1.1
# GET http://localhost:3900/api/v1/admin/users/Active HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdlMTg4ZjczMDE0MjgzZjkwNmQyYyIsImVtYWlsIjoiZW1wbGVhZG9AZ21haWwuY29tIiwicmVnaXN0ZXJfZGF0ZSI6IjIwMjItMDQtMjZUMTI6MTE6NTIuMjc3WiIsImlhdCI6MTY1MTA5MzI2OSwiZXhwIjoxNjUxMTc5NjY5fQ.1Zbnh9Ik4QQHHnewAab0Ug31ZYXm5rzcwwWUaKxQrfQ