
GET http://localhost:3900/api/v1/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzNlYmYzMzAzNGMxNDNlYjI1MDY2ZSIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA1LTA1VDE1OjIzOjMxLjMzOVoiLCJpYXQiOjE2NTE4MzE5ODMsImV4cCI6MTY1MTgzOTE4M30.s5tDUSrziaE_Oum9vZ22MX4qr0qbJ3aYu3iFtxvx4xk