GET http://localhost:3900/api/v1/order/process HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjNmNzIyNjdkNjA0MGNlMzYxNzQ3ZCIsImVtYWlsIjoicHJ1ZWJhT3JkZXJzQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA0LTIzVDEyOjU0OjU4LjUyMVoiLCJpYXQiOjE2NTA3MTg0OTgsImV4cCI6MTY1MDgwNDg5OH0.Es8eg7OqXAYowMAwT2oayltOkNVtu2Ya9DZ7Nkke3GQ