
GET http://localhost:3900/api/v1/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdjYzM1YzUwNjJmOWQyNjJhYjU3ZiIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA0LTI2VDEwOjQwOjUzLjg0OVoiLCJpYXQiOjE2NTA5Njk2NTQsImV4cCI6MTY1MTA1NjA1NH0.409hpV_x5yFuD2e6NKJiEc1Ie8dk_o_PxEICFR08VD0