GET http://localhost:3900/api/v1/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjI3Mjg2ZGY4NjgyMTEyYmU1MmQ2YyIsImVtYWlsIjoiYWRyaWFuNEBnbWFpbC5jb20iLCJyZWdpc3Rlcl9kYXRlIjoiMjAyMi0wNC0yMlQwOToxNjo1NC4wNjVaIiwiaWF0IjoxNjUwNjE5MDE0LCJleHAiOj2NTA3MDU0MTR9.o_u5ZXJJopfAtKrzcS1XQaj0S0d6aAgk4ckr7cG18Zo