GET http://localhost:3900/api/v1/order/cart HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzRmNzlkYTM5MmJiNWNjYzNhNWFkNSIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA1LTA2VDEwOjI1OjMzLjg5MloiLCJpYXQiOjE2NTIxMDgzNzMsImV4cCI6MTY1MjExNTU3M30.90d18fhjS_7IMBamOLQ0Ekxo6aXIcmzCr2UpIoz5Pa4