GET http://localhost:3900/api/v1/cards/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyN2E1YjdjYzBjZTk3OGE5NTIyNDU1NCIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA1LTEwVDEyOjMzOjAwLjcxN1oiLCJpYXQiOjE2NTIxODkwNDIsImV4cCI6MTY1MjE5NjI0Mn0.jTuDHVL7HRm5D5qiF0mGGeOfhmDdMeg1RCfpp_OJAp8