GET http://localhost:3900/api/v1/admin/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdlMTJlMzE5MGJhZDYxODYxZGYwMCIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicmVnaXN0ZXJfZGF0ZSI6IjIwMjItMDQtMjZUMTI6MTA6MjIuMjM2WiIsImlhdCI6MTY1MTA5MzMxNywiZXhwIjoxNjUxMTc5NzE3fQ.VxB5rxwKt9IvRtTqtfsRlrNEups-zzJOWzFDbEeRtrU