GET http://localhost:3900/api/v1/order/6267bb021c40a8e5800c55fd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdiYTU2MWM0MGE4ZTU4MDBjNTVlYiIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA0LTI2VDA5OjI0OjM4LjEwMVoiLCJpYXQiOjE2NTA5NjUwNzgsImV4cCI6MTY1MTA1MTQ3OH0.rcAPCj1e4f8Wdwwghjrzl5c1pGz_1x4Koim_wOCaDrI