GET http://localhost:3900/api/v1/order/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzRmNzlkYTM5MmJiNWNjYzNhNWFkNSIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA1LTA2VDEwOjI1OjMzLjg5MloiLCJpYXQiOjE2NTIwOTk5NjMsImV4cCI6MTY1MjEwNzE2M30.uhxfm-v70vPyiADG1fHd87u41oORY7jIdAZTMq7AyKU