GET http://localhost:3900/api/v1/cards/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjdkNTc2MjRmZDUzYWRiNTE5ZGFmYiIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA0LTI2VDExOjIwOjIyLjc1MVoiLCJpYXQiOjE2NTA5NzIwMjIsImV4cCI6MTY1MTA1ODQyMn0.53--PwnDnpZbwwB-6OWXtPygfR68piuWkUUfj08kch8