PUT http://localhost:3900/api/v1/address/627c166b1dfacd9e9095a71e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyN2MxNWNjMWRmYWNkOWU5MDk1YTYwOSIsImVtYWlsIjoicHJ1ZWJhQGdtYWlsLmNvbSIsInJlZ2lzdGVyX2RhdGUiOiIyMDIyLTA1LTExVDIwOjAwOjEyLjQwNFoiLCJpYXQiOjE2NTIyOTkyMTIsImV4cCI6MTY1MjM4NTYxMn0.0T_wTQM3l_4hpOJ-cASAFQz6nKRGOmyIOl05UqJGK7w

{
    "name" : "Calle Mi Casa 2",
    "number" : "24",
    "floor" : "",
    "name_person" : "Adrián Arnaiz",
    "location" : "Madrid"
}