PUT http://localhost:3900/api/v1/address/62646f0a7b3a7127375c70fc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjJhMTYwZmUxNmNmZjYwMzVmZjJhOSIsImVtYWlsIjoiYWRyaWFuNUBnbWFpbC5jb20iLCJyZWdpc3Rlcl9kYXRlIjoiMjAyMi0wNC0yMlQxMjozNjo0OC4wNjRaIiwiaWF0IjoxNjUwNjMxMDA4LCJleHAiOjE2NTA3MTc0MDh9.CisnZG9PFIsyaaCgjl5LEoF6m2kPqafauJCU_lF224c

{
    "name" : "",
    "number" : "",
    "floor" : "0",
    "name_person" : "",
    "location" : ""
}